export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "About",
  headline: "Aavishkar",
  description:
    "Aavishkaar is a National Level Technical Symposium which creates a platform for technical and non - technical events. With an aim to link an idea through innovation, it presents Tech Expo and Dhishan. These events represents the idea- diversifying concoction, along with the entertainment. ",
  buttonLabel: "Get Started",
  imgStart: false,
  img: require("../../images/undraw_pair_programming_re_or4x.svg").default,
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
  href: '../../pages/Dhishan.js'
};
export const homeObjTwo = {
  id: "discuss",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Dhishan",
  headline: "lorem ipsum",
  description:
    "Connect with your Fellow students. Discuss, Write and Resolve issues ",
  buttonLabel: "Learn More",
  imgStart: true,
  img: require("../../images/undraw_co-working_re_w93t.svg").default,
  alt: "Car",
  dark: false,
  primary: false,
  darkText: true,
  href: "../../pages/Dhishan.js",
};
export const homeObjFour = {
  id: "Leaderboard",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Tech-Expo",
  headline: "Without the spur of competition we'd loaf out our life.",
  description:
    "A healthy competition helps us grow faster and also helps the community to enhance itself",
  buttonLabel: "Learn More",
  imgStart: true,
  img: require("../../images/undraw_grades_re_j7d6.svg").default,
  alt: "Car",
  dark: false,
  primary: false,
  darkText: true,
  href: "../../pages/Dhishan.js",
};
export const homeObjFive = {
  id: "Resources",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Tech-Expo",
  headline: "Learning never exhausts the mind !!",
  description:
    "Explore the previous sessions, Webinars and Notes provided by the community members ",
  buttonLabel: "Learn More",
  imgStart: false,
  img: require("../../images/undraw_road_to_knowledge_m8s0.svg").default,
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
  href: "../../pages/Dhishan.js",
};
export const homeObjThree = {
  id: "contact",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Connect With Us",
  headline: "Get in Touch with us...",
  description:
    "We are always looking forward for collabration and interesting projects. Feel free to connect",
  buttonLabel: "Connect",
  imgStart: true,
  img: require("../../images/undraw_community_re_cyrm.svg").default,
  alt: "Papers",
  dark: false,
  primary: false,
  darkText: true,
  href: "../../pages/Dhishan.js",
};
